### ISSUE TITLE
Error: Cannot find module './eiows_linux_108'

### ISSUE THREAD

**Issue by jt1971** [hoobs-org/HOOBS#1850]
**Description**
Recently updated by Raspberry Pi and HOOBS web interface not working.
Deleted and reinstalled HOOBS, using sudo apt install hoobsd hoobs-cli hoobs-gui
When enter sudo hbs install, "Error: Cannot find module './eiows_linux_108'

**Version**
4.1

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ X] No

**Pervious version**
If you upgraded, please let us know your previous version.

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ ] HOOBS SD Card
- [ X] Custom Install

**If this is a custom install, what's your operating system?**
RaspberryPi4

**List your plugins**
Vanilla install with no plugins

**Post your config**
[This can be found in the interface, Configuration -> Advanced or you can get it via SSH `cat ~/.hoobs/etc/config.json`](
cat: /home/pi/.hoobs/etc/config.json: No such file or directory

**Post your log**
hoobsd/HBS is not starting and therefore no log.

node v18.13.0
npm 9.3.0
Linux raspberrypi4 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux

**Comment by aaryavbehl** [comment]
![image](https://user-images.githubusercontent.com/88878743/212566227-1982eb0f-2047-4ccc-b876-e85330451199.png)
Even I am getting the same error

**Comment by cronusfortunam** [comment]
same here help

**Comment by konistehrad** [comment]
Experiencing this on a Raspberry Pi 4 running Ubuntu 22.10 64-bit.

**Comment by DarkGrey88** [comment]
The same. Debian 11

**Comment by DarkGrey88** [comment]
after update node js from 18.3 to 19.5 
Error: Error: Cannot find module './eiows_linux_111'

lib/hoobsd/node_modules/eiows/

in this folder i have only
eiows_linux_93.node

**Comment by DarkGrey88** [comment]
ok
remove js

 sudo apt remove nodejs

after fix it

 curl -sk https://dl.hoobs.org/fix | sudo bash -


It will install js 16.x
