### ISSUE TITLE
Skybell plug-in not working with HOOBS 3.2

### ISSUE THREAD

**Issue by Nisse57** [hoobs-org/HOOBS#617]
How can I see which HB version HOOBS is using? I get SIGTERM when using the latest Skybell plugin version 2.0.0 (https://github.com/thoukydides/homebridge-skybell). The Skybell plug-in states that it require HB 1.0.4. The previous Skybell version 1.8.0 worked fine with HOOBS 3.1.27. Here is the error log:
5/7/2020, 11:28:43 AM - [SkyBell] addAccessory 'Xalet Front Door'
5/7/2020, 11:28:43 AM - [SkyBell] new SkyBellAccessory 'Xalet Front Door': type='skybell hd'
5/7/2020, 11:28:43 AM - [SkyBell] new SkyBellCameraStream 'Xalet Front Door'
5/7/2020, 11:28:43 AM - TypeError: this.accessory.configureController is not a function
    at new SkyBellAccessory (/home/hoobs/.hoobs/node_modules/homebridge-skybell/accessory.js:155:24)
    at SkyBellPlatform.addAccessory (/home/hoobs/.hoobs/node_modules/homebridge-skybell/index.js:72:23)
    at SkyBellAccount.addDevice (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:81:22)
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:65:54
    at Array.forEach (<anonymous>)
    at SkyBellAccount.gotDevices (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:62:17)
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:50:22
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_api.js:205:21
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_api.js:236:24)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
5/7/2020, 11:28:43 AM - Got SIGTERM, shutting down Bridge...

**Comment by BobbySlope** [comment]
installing v 2.0.1 works ti install but still errors:

Here is the error : 5/8/2020, 9:19:21 AM - TypeError: this.accessory.configureController is not a function
    at new SkyBellAccessory (/home/hoobs/.hoobs/node_modules/homebridge-skybell/accessory.js:155:24)
    at SkyBellPlatform.addAccessory (/home/hoobs/.hoobs/node_modules/homebridge-skybell/index.js:81:23)
    at SkyBellAccount.addDevice (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:81:22)
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:65:54
    at Array.forEach (<anonymous>)
    at SkyBellAccount.gotDevices (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:62:17)
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:50:22
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_api.js:205:21
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_api.js:236:24)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)

**Comment by BobbySlope** [comment]
for me the plugin is registering as "Home-Connect", for @Nisse57 its registering as "SkyBell" as it should, but still errors

**Comment by jlq76** [comment]
Same issue here when adding the Skybell plugin.
- Hoobs Version 3.2.3
- Node Version 12.13.1


`5/11/2020, 12:01:43 PM TypeError: this.accessory.configureController is not a function
    at new SkyBellAccessory (/home/hoobs/.hoobs/node_modules/homebridge-skybell/accessory.js:155:24)
    at SkyBellPlatform.addAccessory (/home/hoobs/.hoobs/node_modules/homebridge-skybell/index.js:81:23)
    at SkyBellAccount.addDevice (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:81:22)
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:65:54
    at Array.forEach (<anonymous>:null:null)
    at SkyBellAccount.gotDevices (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:62:17)
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_account.js:50:22
    at /home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_api.js:205:21
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-skybell/skybell_api.js:236:24)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by mkellsy** [comment]
We have a fix for this in version 3.2.4

**Comment by Nisse57** [comment]
Update to version 3.2.4 does not work. I get the following message:
5/15/2020, 6:43:03 PM - Got SIGINT, shutting down Bridge...
5/15/2020, 6:43:17 PM - /usr/local/bin/hoobs -> /usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs
5/15/2020, 6:43:17 PM - + @hoobs/hoobs@3.2.4
updated 1 package in 9.591s
5/15/2020, 6:44:04 PM - [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
5/15/2020, 6:44:04 PM - [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826
5/15/2020, 6:44:04 PM - [Refresh Services] connect ECONNREFUSED 127.0.0.1:51826

HOOBS Service is not running after the update attempt. When I start the service I'm still on 3.2.3

However, the SkyBell plugin now works just fine!?
5/15/2020, 6:49:03 PM - Loaded plugin "homebridge-automation-switches".
5/15/2020, 6:49:03 PM - Loaded plugin "homebridge-skybell".
5/15/2020, 6:49:04 PM - Loaded plugin "homebridge-telldus".
5/15/2020, 6:49:04 PM - [Tells Live!] isLocal: true
5/15/2020, 6:49:04 PM - [Tells Live!] Loading accessories...
5/15/2020, 6:49:04 PM - [SkyBell] new SkyBellPlatform
5/15/2020, 6:49:04 PM - [SkyBell] Homebridge API 2.5 (package version 3.2.4)
5/15/2020, 6:49:04 PM - [AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
5/15/2020, 6:49:04 PM - [AutomationSwitches] Found automation switch in config: "Blinds-up"
5/15/2020, 6:49:04 PM - [AutomationSwitches] Switch Blinds-up is stored in file alarmclock.5AE9710578AB.json
5/15/2020, 6:49:04 PM - [AutomationSwitches] Timezone is undefined
5/15/2020, 6:49:04 PM - [AutomationSwitches] Local time is 5/15/2020, 6:49:04 PM
5/15/2020, 6:49:04 PM - [AutomationSwitches] UTC time is Fri, 15 May 2020 16:49:04 GMT
5/15/2020, 6:49:04 PM - [AutomationSwitches] Raising next alarm at 5/16/2020, 6:50:00 AM
5/15/2020, 6:49:04 PM - [AutomationSwitches] Initializing platform accessory "Blinds-up"...
5/15/2020, 6:49:04 PM - Load homebridge-switches.AutomationSwitches
5/15/2020, 6:49:04 PM - [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
5/15/2020, 6:49:04 PM - [SkyBell] finishedLaunching
5/15/2020, 6:49:04 PM - [Tells Live!] Found 0 sensors in telldus live.
5/15/2020, 6:49:04 PM - [Tells Live!] Found 22 devices in telldus live.
5/15/2020, 6:49:05 PM - [SkyBell] addAccessory 'Xalet Front Door'
5/15/2020, 6:49:05 PM - [SkyBell] new SkyBellAccessory 'Xalet Front Door': type='skybell hd'
5/15/2020, 6:49:06 PM - [SkyBell] new SkyBellCameraStream 'Xalet Front Door'
5/15/2020, 6:49:06 PM - Xalet Front Door is running on port 42783.

**Comment by mkellsy** [comment]
Try rebooting

**Comment by Nisse57** [comment]
That solved it. I assumed the update would reboot if necessary, but I should have tried it anyway. Sorry. All is good now. Thanks!

**Comment by mkellsy** [comment]
This is a known issue. Working on a fix for the next version
